Repository NLog/NLog.Extensions.Logging, pull requests merged in 2018-05, with the labels that each got.

#214 CodeCov integration
  appveyor.yml
  examples/NetCore2/ConsoleExample/ConsoleExample.csproj
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
  test/NLog.Extensions.Logging.Tests.csproj
Labels: build

#215 Added Sonar
  appveyor.yml
  run-sonar.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: build

#217 Update NLog dependency, exclude NLog 5 pre-releases
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: bug, enhancement

#219 Release 1.0.2
  CHANGELOG.MD
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: version

#213 MessageProperties - Added support for using NLog MessageTemplate Parser
  src/NLog.Extensions.Logging/Logging/NLogLogger.cs
  src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
  src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs
  src/NLog.Extensions.Logging/Properties/AssemblyInfo.cs
  test/CustomLoggerCallSiteTest.cs
  test/CustomLoggerPropertyTest.cs
  test/LoggerTests.cs
  test/NLog.Extensions.Logging.Tests.csproj
  test/NLog.snk
  test/NLogMessageParameterListTests.cs
Labels: Feature

#222 Updated NLog version, release 1.1
  CHANGELOG.MD
  appveyor.yml
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: version
