Repository NLog/NLog.Extensions.Logging, pull requests merged in 2018-08, with the labels that each got.

#232 BeginScope: support for non-serializable objects + performance improvement (20-50% cpu, 35% times less allocations)
  examples/NetCore2/ConsoleExample/Program.cs
  src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
  src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
  src/NLog.Extensions.Logging/Logging/NLogLogger.cs
  src/NLog.Extensions.Logging/Logging/NLogLoggerFactory.cs
  src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs
  src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
  src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
  test/CustomBeginScopeTest.cs
  test/CustomLoggerPropertyTest.cs
Labels: enhancement, performance

#233 Fixed null-reference-exception when parsing empty scope-property collection
  src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
  src/NLog.Extensions.Logging/Logging/NLogLogger.cs
  src/NLog.Extensions.Logging/Logging/NLogLoggerFactory.cs
  src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs
  test/CustomBeginScopeTest.cs
Labels: enhancement

#235 Update NLog dependency
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: enhancement

#234 Version 1.2.1
  CHANGELOG.MD
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: version

#236 BeginScope always return scope-object even on error
  src/NLog.Extensions.Logging/Logging/NLogLogger.cs
Labels: enhancement
