Repository NLog/NLog.Extensions.Logging, pull requests merged in 2018-07, with the labels that each got.

#223 BeginScope accepts any type of KeyValuePair and Dictionary
  src/NLog.Extensions.Logging/Logging/NLogLogger.cs
  test/LoggerTests.cs
Labels: Feature

#227 Update NLog dependency
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: enhancement

#228 Version 1.2
  CHANGELOG.MD
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: version

#229 BeginScope should accept any type of KeyValuePair (Swallow exceptions)
  src/NLog.Extensions.Logging/Logging/NLogLogger.cs
Labels: enhancement
