Repository NLog/NLog.Extensions.Logging, pull requests merged in 2018-09, with the labels that each got.

#246 Fixing bug throwing ArgumentOutOfRangeException if input is empty list
  src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
  test/NLog.Extensions.Logging.Tests/NLogMessageParameterListTests.cs
Labels: bug

#245 Added ${configsetting} for appsettings.json and others
  .travis.yml
  NLog.Extensions.Logging.sln
  appveyor.yml
  build.ps1
  src/NLog.Extensions.Configuration/ConfigSettingLayoutRenderer.cs
  src/NLog.Extensions.Configuration/NLog.Extensions.Configuration.csproj
  src/NLog.Extensions.Configuration/Properties/AssemblyInfo.cs
  test/NLog.Extensions.Configuration.Tests/ConfigSettingLayoutRendererTests.cs
  test/NLog.Extensions.Configuration.Tests/NLog.Extensions.Configuration.Tests.csproj
  test/NLog.Extensions.Configuration.Tests/Properties/AssemblyInfo.cs
  test/NLog.Extensions.Configuration.Tests/appsettings.json
Labels: Feature

#247 Version 1.3
  CHANGELOG.MD
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: version
