Repository NLog/NLog.Extensions.Logging, pull requests merged in 2019-05, with the labels that each got.

#296 Deploy snupkg on AppVeyor natively
  appveyor.yml
Labels: build

#297 Remove old install in AppVeyor script
  appveyor.yml
Labels: build

#289 NLogBeginScopeParser - Refactoring and improved exception handling
  build.ps1
  src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
  src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
  src/NLog.Extensions.Logging/Logging/NLogLogger.cs
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: enhancement, refactor

#299 Update dependency NLog ver. 4.6.4
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: dependencies, merge when passing
