Repository NLog/NLog.Extensions.Logging, pull requests merged in 2019-09, with the labels that each got.

#325 ILoggingBuilder AddNLog extension method with correct dispose and no double logging
  src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
  src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
  test/NLog.Extensions.Hosting.Tests/ExtensionMethodTests.cs
Labels: bug, enhancement, size/M

#327 NLog.Extension.Logging.Tests - Stop using static LogManager
  src/NLog.Extensions.Logging/Logging/NLogLoggerFactory.cs
  src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs
  test/NLog.Extensions.Logging.Tests/CustomBeginScopeTest.cs
  test/NLog.Extensions.Logging.Tests/CustomLoggerCallSiteTest.cs
  test/NLog.Extensions.Logging.Tests/CustomLoggerPropertyTest.cs
  test/NLog.Extensions.Logging.Tests/LoggerTests.cs
  test/NLog.Extensions.Logging.Tests/Logging/NLogLoggerFactoryTests.cs
  test/NLog.Extensions.Logging.Tests/Logging/NLogLoggerProviderTests.cs
  test/NLog.Extensions.Logging.Tests/NLogMessageParameterListTests.cs
  test/NLog.Extensions.Logging.Tests/NLogTestBase.cs
Labels: enhancement, size/L, tests

#328 Cleanup test code
  test/NLog.Extensions.Logging.Tests/ConfigSettingLayoutRendererTests.cs
  test/NLog.Extensions.Logging.Tests/CustomBeginScopeTest.cs
  test/NLog.Extensions.Logging.Tests/CustomLoggerCallSiteTest.cs
  test/NLog.Extensions.Logging.Tests/CustomLoggerPropertyTest.cs
  test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs
  test/NLog.Extensions.Logging.Tests/LoggerTests.cs
  test/NLog.Extensions.Logging.Tests/Logging/NLogLoggerFactoryTests.cs
  test/NLog.Extensions.Logging.Tests/Logging/NLogLoggerProviderTests.cs
  test/NLog.Extensions.Logging.Tests/NLogTestBase.cs
  test/NLog.Extensions.Logging.Tests/Properties/AssemblyInfo.cs
Labels: refactor

#329 Improve code complexity
  src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
Labels: refactor, size/S

#331 Create ranger.yml
  .github/ranger.yml
Labels: size/S

#330 Release 1.5.4
  CHANGELOG.MD
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: Patch Version, merge when passing, release, size/XS

#333 NLogMessageParameterList - Reduce code complexity for IsValidParameterList
  src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
  src/NLog.Extensions.Logging/Logging/NLogLogger.cs
  src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
  test/NLog.Extensions.Logging.Tests/NLogMessageParameterListTests.cs
Labels: refactor, size/M

#334 NLogMessageParameterList - Reduce code complexity for IsValidParameterList
  src/NLog.Extensions.Logging/Logging/NLogMessageParameterList.cs
Labels: size/XS

#342 ILoggerFactory is obsolete in .NET Core 3. Instead use ILoggingBuilder.AddNLog
  CHANGELOG.MD
  build.ps1
  src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
  test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs
Labels: size/S

#344 Introduce AddNLog with NLog-config parameter
  src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
  src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
  test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs
Labels: size/M
