Repository NLog/NLog.Extensions.Logging, pull requests merged in 2019-10, with the labels that each got.

#332 Support .NET Core 3.0, remove Travis integration
  .travis.yml
  README.md
  appveyor.yml
  build.ps1
  src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
  test/NLog.Extensions.Hosting.Tests/NLog.Extensions.Hosting.Tests.csproj
  test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj
Labels: Feature, build, size/M

#345 Added AddNLog with functor to create/initialize LogFactory for NLogLoggingProvider
  src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
  test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs
Labels: size/M

#347 Version 1.6 and changelog
  CHANGELOG.MD
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: size/S

#350 Fixed conflict issue between UseNLog and default log providers
  src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
Labels: bug, size/S

#351 Version 1.6.1
  CHANGELOG.MD
  build.ps1
Labels: release
