Repository NLog/NLog.Extensions.Logging, pull requests merged in 2019-04, with the labels that each got.

#263 Load JSON based NLog config (e.g. declared in appsettings.json) + BeginScopeParser performance improvements
  NLog.Extensions.Logging.sln
  build.ps1
  examples/NetCore2/ConsoleExample/ConsoleExample.csproj
  examples/NetCore2/ConsoleExample/Program.cs
  examples/NetCore2/ConsoleExample/appsettings.json
  src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
  src/NLog.Extensions.Logging/Internal/StringExtensions.cs
  src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
  src/NLog.Extensions.Logging/Logging/NLogLogger.cs
  src/NLog.Extensions.Logging/Logging/NLogLoggerProvider.cs
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj.DotSettings
  test/NLog.Extensions.Logging.Tests/ConfigSettingLayoutRendererTests.cs
  test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj
  test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs
Labels: Feature, performance

#285 Deploy snupkg on AppVeyor
  appveyor.yml
Labels: build

#283 NLogLoggingConfiguration - Added support for default-wrapper, default-target-parameter & autoReload
  examples/NetCore2/ConsoleExample/Program.cs
  src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
  test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs
Labels: Feature

#286 NLogLoggingConfiguration - Support KeepVariablesOnReload
  src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
  test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs
Labels: Feature
