Repository NLog/NLog.Extensions.Logging, pull requests merged in 2020-05, with the labels that each got.

#419 Reading JSON config - Trim keys as Json allows spaces in keys
  src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
  test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs
Labels: enhancement, size/M

#418 Renaming LoadNLogConfigFromSection to LoadConfigurationFromSection
  examples/NetCore2/ConsoleExampleJsonConfig/Program.cs
  src/NLog.Extensions.Logging/Config/SetupBuilderExtensions.cs
  test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs
Labels: size/S

#422 Version 1.6.3
  CHANGELOG.MD
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: Minor Version, release

#423 LogFactory.Setup - Make RegisterConfigSettings public
  src/NLog.Extensions.Logging/Config/SetupExtensionsBuilderExtensions.cs
Labels: size/XS

#424 Update NLog to 4.7.1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: dependencies, size/XS

#427 Updated example applications to use LogManager.Setup()
  examples/NetCore2/ConsoleExample/Program.cs
  examples/NetCore2/ConsoleExampleJsonConfig/Program.cs
  examples/NetCore2/HostingExample/Program.cs
Labels: size/M

#428 Release 1.6.4
  CHANGELOG.MD
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: release, size/S

#429 Fix documentation of default EventIdSeparator
  src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs
Labels: docs, refactor, size/S
