Repository NLog/NLog.Extensions.Logging, pull requests merged in 2020-12, with the labels that each got.

#461 Move to PackageIcon and PackageLicenseExpression for NuGet package
  src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: size/S

#457 Update NuGet API key
  appveyor.yml
Labels: size/XS, squash when passing

#456 Added NLogProviderOptions.IncludeActivtyIdsWithBeginScope, added .NET 5 build, move tests to .NET Core LTS
  appveyor.yml
  build.ps1
  src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
  src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
  src/NLog.Extensions.Logging/Logging/ActivityExtensions.cs
  src/NLog.Extensions.Logging/Logging/NLogBeginScopeParser.cs
  src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
  test/NLog.Extensions.Hosting.Tests/NLog.Extensions.Hosting.Tests.csproj
  test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj
Labels: Feature, size/L, squash when passing

#462 Release 1.7.0
  CHANGELOG.MD
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: release, size/S, squash when passing

#463 Added unit-test for NLogProviderOptions.IncludeActivtyIdsWithBeginScope
  test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs
Labels: size/S, tests
