Repository NLog/NLog.Extensions.Logging, pull requests merged in 2020-03, with the labels that each got.

#393 AddNLog overload with NLogProviderOptions and LoggingConfiguration
  src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
  test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs
Labels: size/M

#407 Improve AddNLog with LoggingConfiguration to handle custom LogFactory
  src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
Labels: enhancement, size/XS

#408 Update NLog dependency to 4.6.8
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: dependencies, size/XS, squash when passing

#409 Version 1.6.2
  CHANGELOG.MD
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: Patch Version, release, size/XS

#410 Introduced SetupExtensionLogging extension method for LogFactory.Setup
  examples/NetCore2/ConsoleExampleJsonConfig/Program.cs
  src/NLog.Extensions.Logging/Config/ISetupLoggerProviderBuilder.cs
  src/NLog.Extensions.Logging/Config/SetupBuilderExtensions.cs
  src/NLog.Extensions.Logging/Config/SetupLoggerProviderBuilderExtensions.cs
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
  test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs
Labels: size/L

#412 Reverted #410 and instead introduced LoadNLogConfigFromSection on ISetupBuilder
  examples/NetCore2/ConsoleExampleJsonConfig/Program.cs
  src/NLog.Extensions.Logging/Config/ISetupLoggerProviderBuilder.cs
  src/NLog.Extensions.Logging/Config/SetupBuilderExtensions.cs
  src/NLog.Extensions.Logging/Config/SetupExtensionsBuilderExtensions.cs
  src/NLog.Extensions.Logging/Config/SetupLoggerProviderBuilderExtensions.cs
  test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs
Labels: size/M
