Repository NLog/NLog.Extensions.Logging, pull requests merged in 2021-02, with the labels that each got.

#474 Update README.md
  README.md
Labels: size/XS

#476 MicrosoftILoggerTarget - Add support for override LoggerName when using ILoggerFactory
  src/NLog.Extensions.Logging/Targets/MicrosoftILoggerTarget.cs
  test/NLog.Extensions.Logging.Tests/MicrosoftILoggerTargetTests.cs
Labels: size/M

#478 Release 1.7.1
  CHANGELOG.MD
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: release

#480 Remove old Patch version script
  patchFileVersion.ps1
Labels: build, size/M

#481 Create PR packages with PR suffix
  build.ps1
Labels: build, size/M

#479 Enable deterministic build
  build.ps1
  src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: build, enhancement, size/S
