Repository NLog/NLog.Extensions.Logging, pull requests merged in 2021-03, with the labels that each got.

#482 NLogProviderOptions - Added ReplaceLoggerFactory and RemoveLoggerFactoryFilter
  src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
  src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
  src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
  src/NLog.Extensions.Logging/Internal/RegisterNLogLoggingProvider.cs
  src/NLog.Extensions.Logging/Logging/NLogLoggerFactory.cs
  src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
  test/NLog.Extensions.Hosting.Tests/ExtensionMethodTests.cs
  test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs
Labels: Feature, size/L

#488 NLogLoggingConfiguration support custom section names
  src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
  test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs
Labels: enhancement, size/M

#490 MicrosoftConsoleLayoutRenderer - For Hosting Lifetime Startup Messages
  src/NLog.Extensions.Logging/LayoutRenderers/MicrosoftConsoleLayoutRenderer.cs
  test/NLog.Extensions.Logging.Tests/MicrosoftConsoleLayoutRendererTest.cs
Labels: Feature, size/L

#497 Release 1.7.2
  CHANGELOG.MD
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: Minor Version, release, size/S

#494 Fix SonarQube Scanning
  appveyor.yml
  run-sonar.ps1
Labels: build, size/M
