Repository NLog/NLog.Extensions.Logging, pull requests merged in 2021-12, with the labels that each got.

#557 Update NuGet API key
  appveyor.yml
Labels: build, size/XS

#558 Bump to Visual Studio 2022 on AppVeyor + Removed .NET core 1 tests
  appveyor.yml
  test/NLog.Extensions.Logging.Tests/ConfigSettingLayoutRendererTests.cs
  test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs
  test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj
  test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs
Labels: build, size/S

#559 NLogLogger - Reduce complexity of CreateLogEventInfo
  src/NLog.Extensions.Logging/Logging/NLogLogger.cs
Labels: refactor, size/XS

#554 NLogProviderOptions with support for CaptureEventId.EventId + EventName
  src/NLog.Extensions.Logging/LayoutRenderers/MicrosoftConsoleLayoutRenderer.cs
  src/NLog.Extensions.Logging/Layouts/MicrosoftConsoleJsonLayout.cs
  src/NLog.Extensions.Logging/Logging/EventIdCaptureType.cs
  src/NLog.Extensions.Logging/Logging/NLogLogger.cs
  src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs
  test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs
  test/NLog.Extensions.Logging.Tests/nlog.config
Labels: breaking change, size/L

#560 Version 5.0 Release Candidate 1
  CHANGELOG.MD
  appveyor.yml
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: Major Version, size/M

#561 Added Getting started for ASP.NET Core 6
  README.md
Labels: docs, size/XS

#562 Simplified example applications to match docs on wiki
  examples/NetCore2/ConsoleExample/ConsoleExample.csproj
  examples/NetCore2/ConsoleExample/Program.cs
  examples/NetCore2/ConsoleExampleJsonConfig/ConsoleExampleJsonConfig.csproj
  examples/NetCore2/ConsoleExampleJsonConfig/Program.cs
Labels: docs, size/M

#563 Removed known issues, since NLog5 makes it as designed
  README.md
Labels: docs, size/M
