Repository NLog/NLog.Extensions.Logging, pull requests merged in 2021-08, with the labels that each got.

#515 Disable ImplicitNuGetFallbackFolder for tests - fixes NU3005 on AppVeyor
  test/NLog.Extensions.Hosting.Tests/NLog.Extensions.Hosting.Tests.csproj
  test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj
Labels: build, size/XS

#517 Added Release drafter action
  .github/release-drafter.yml
  .github/workflows/changelog.yml
Labels: size/M, skip-changelog

#524 Version 5.0 preview 1
  CHANGELOG.MD
  appveyor.yml
  build.ps1
  src/NLog.Extensions.Hosting/NLog.Extensions.Hosting.csproj
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: release, size/M

#529 NLogLoggerProvider - Always load from appsettings when possible
  src/NLog.Extensions.Hosting/Extensions/ConfigureExtensions.cs
  src/NLog.Extensions.Logging/Extensions/ConfigureExtensions.cs
Labels: enhancement, size/S
