Repository NLog/NLog.Extensions.Logging, pull requests merged in 2022-05, with the labels that each got.

#589 Bump Microsoft.NET.Test.Sdk from 17.1.0 to 17.2.0
  test/NLog.Extensions.Hosting.Tests/NLog.Extensions.Hosting.Tests.csproj
  test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj
Labels: dependencies, size/XS

#591 Version 5.0 RTM
  CHANGELOG.MD
  build.ps1
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
Labels: Major Version, size/M

#593 Fix typo in xml-docs for MicrosoftConsoleJsonLayout
  src/NLog.Extensions.Logging/Layouts/MicrosoftConsoleJsonLayout.cs
Labels: size/XS
