Repository NLog/NLog.Extensions.Logging, pull requests merged in 2022-02, with the labels that each got.

#567 Extend RegisterConfigSettings to also register MicrosoftConsoleLayoutRenderer
  src/NLog.Extensions.Logging/Config/SetupExtensionsBuilderExtensions.cs
Labels: enhancement, size/XS

#570 Ensure event ID out of mapper range is parsed
  src/NLog.Extensions.Logging/LayoutRenderers/MicrosoftConsoleLayoutRenderer.cs
  test/NLog.Extensions.Logging.Tests/MicrosoftConsoleLayoutRendererTest.cs
Labels: bug, size/S

#571 MicrosoftConsoleJsonLayout - Fixed IndexOutOfRangeException when large EventID
  src/NLog.Extensions.Logging/LayoutRenderers/MicrosoftConsoleLayoutRenderer.cs
  src/NLog.Extensions.Logging/Layouts/MicrosoftConsoleJsonLayout.cs
  test/NLog.Extensions.Logging.Tests/MicrosoftConsoleJsonLayoutTests.cs
Labels: bug, size/M

#572 MicrosoftConsoleLayoutRenderer - Skip string-allocation for EventId when possible on platform
  src/NLog.Extensions.Logging/LayoutRenderers/MicrosoftConsoleLayoutRenderer.cs
Labels: performance, size/M

#573 MicrosoftConsoleLayoutRenderer - Improve handling of TimestampFormat
  src/NLog.Extensions.Logging/LayoutRenderers/MicrosoftConsoleLayoutRenderer.cs
Labels: refactor, size/XS

#574 Bump Microsoft.NET.Test.Sdk from 16.2.0 to 16.9.4
  src/NLog.Extensions.Logging/NLog.Extensions.Logging.csproj
  test/NLog.Extensions.Hosting.Tests/NLog.Extensions.Hosting.Tests.csproj
  test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj
Labels: dependencies, size/S
