Repository NLog/NLog.Extensions.Logging, pull requests merged in 2024-02, with the labels that each got.

#726 Bump xunit from 2.4.0 to 2.7.0
  appveyor.yml
  run-sonar.ps1
  test/NLog.Extensions.Hosting.Tests/NLog.Extensions.Hosting.Tests.csproj
  test/NLog.Extensions.Logging.Tests/CustomBeginScopeTest.cs
  test/NLog.Extensions.Logging.Tests/Extensions/ConfigureExtensionsTests.cs
  test/NLog.Extensions.Logging.Tests/MicrosoftILoggerTargetTests.cs
  test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj
  test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs
Labels: build-config, dependencies, size/M

#727 Bump xunit from 2.4.0 to 2.7.0 (sonar version)
  run-sonar.ps1
Labels: size/XS

#724 Skipping empty config sections without throwing exceptions
  src/NLog.Extensions.Logging/Config/NLogLoggingConfiguration.cs
  test/NLog.Extensions.Logging.Tests/NLog.Extensions.Logging.Tests.csproj
  test/NLog.Extensions.Logging.Tests/NLogLoggingConfigurationTests.cs
Labels: size/M

#728 Downgrade dotnet-sonarscanner to ver. 5.15 because of java version
  appveyor.yml
  run-sonar.ps1
Labels: size/XS
